config/routes.rb
Rails.application.routes.draw do
  resources :slideshows
  resources :auteurs
  resources :firsts
  resources :arts
  root to: "arts#index" # redirige vers arts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
end

app/models/auteur.rb
class Auteur < ApplicationRecord
end

app/models/first.rb
class First < ApplicationRecord
end

app/models/slideshow.rb
class Slideshow < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:author, :title, :date, :dimensions, :photo, :comments)
    end
end

app/controllers/auteurs_controller.rb
class AuteursController < ApplicationController
  before_action :set_auteur, only: [:show, :edit, :update, :destroy]

  # GET /auteurs
  # GET /auteurs.json
  def index
    @auteurs = Auteur.all
  end

  # GET /auteurs/1
  # GET /auteurs/1.json
  def show
  end

  # GET /auteurs/new
  def new
    @auteur = Auteur.new
  end

  # GET /auteurs/1/edit
  def edit
  end

  # POST /auteurs
  # POST /auteurs.json
  def create
    @auteur = Auteur.new(auteur_params)

    respond_to do |format|
      if @auteur.save
        format.html { redirect_to @auteur, notice: 'Auteur was successfully created.' }
        format.json { render :show, status: :created, location: @auteur }
      else
        format.html { render :new }
        format.json { render json: @auteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auteurs/1
  # PATCH/PUT /auteurs/1.json
  def update
    respond_to do |format|
      if @auteur.update(auteur_params)
        format.html { redirect_to @auteur, notice: 'Auteur was successfully updated.' }
        format.json { render :show, status: :ok, location: @auteur }
      else
        format.html { render :edit }
        format.json { render json: @auteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auteurs/1
  # DELETE /auteurs/1.json
  def destroy
    @auteur.destroy
    respond_to do |format|
      format.html { redirect_to auteurs_url, notice: 'Auteur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auteur
      @auteur = Auteur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auteur_params
      params.require(:auteur).permit(:author, :photo)
    end
end

app/controllers/firsts_controller.rb
class FirstsController < ApplicationController
  before_action :set_first, only: [:show, :edit, :update, :destroy]

  # GET /firsts
  # GET /firsts.json
  def index
    @firsts = First.all
  end

  # GET /firsts/1
  # GET /firsts/1.json
  def show
  end

  # GET /firsts/new
  def new
    @first = First.new
  end

  # GET /firsts/1/edit
  def edit
  end

  # POST /firsts
  # POST /firsts.json
  def create
    @first = First.new(first_params)

    respond_to do |format|
      if @first.save
        format.html { redirect_to @first, notice: 'First was successfully created.' }
        format.json { render :show, status: :created, location: @first }
      else
        format.html { render :new }
        format.json { render json: @first.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firsts/1
  # PATCH/PUT /firsts/1.json
  def update
    respond_to do |format|
      if @first.update(first_params)
        format.html { redirect_to @first, notice: 'First was successfully updated.' }
        format.json { render :show, status: :ok, location: @first }
      else
        format.html { render :edit }
        format.json { render json: @first.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firsts/1
  # DELETE /firsts/1.json
  def destroy
    @first.destroy
    respond_to do |format|
      format.html { redirect_to firsts_url, notice: 'First was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first
      @first = First.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_params
      params.require(:first).permit(:name)
    end
end

app/controllers/slideshows_controller.rb
class SlideshowsController < ApplicationController
  before_action :set_slideshow, only: [:show, :edit, :update, :destroy]

  # GET /slideshows
  # GET /slideshows.json
  def index
    @slideshows = Slideshow.all
  end

  # GET /slideshows/1
  # GET /slideshows/1.json
  def show
  end

  # GET /slideshows/new
  def new
    @slideshow = Slideshow.new
  end

  # GET /slideshows/1/edit
  def edit
  end

  # POST /slideshows
  # POST /slideshows.json
  def create
    @slideshow = Slideshow.new(slideshow_params)

    respond_to do |format|
      if @slideshow.save
        format.html { redirect_to @slideshow, notice: 'Slideshow was successfully created.' }
        format.json { render :show, status: :created, location: @slideshow }
      else
        format.html { render :new }
        format.json { render json: @slideshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slideshows/1
  # PATCH/PUT /slideshows/1.json
  def update
    respond_to do |format|
      if @slideshow.update(slideshow_params)
        format.html { redirect_to @slideshow, notice: 'Slideshow was successfully updated.' }
        format.json { render :show, status: :ok, location: @slideshow }
      else
        format.html { render :edit }
        format.json { render json: @slideshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slideshows/1
  # DELETE /slideshows/1.json
  def destroy
    @slideshow.destroy
    respond_to do |format|
      format.html { redirect_to slideshows_url, notice: 'Slideshow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slideshow
      @slideshow = Slideshow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slideshow_params
      params.require(:slideshow).permit(:author, :photo, :description, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/auteurs_helper.rb
module AuteursHelper
end

app/helpers/firsts_helper.rb
module FirstsHelper
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/views/arts/_form.html.erb
<div class="container" >
<%= simple_form_for @art do |f| %>


  <%= f.input :author%>
  <%= f.input :title%>
  <%= f.input :date%>
  <%= f.input :dimensions%>
  <%= f.input :photo%>
  <%= f.input :comments%>
  <%= f.button :submit %>
<% end %>
</div>

app/views/arts/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">Horror's Museum</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/">Accueil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/slideshows">Auteurs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/auteurs">Oeuvres</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>
  </div>
</nav>


<h1></h1>

<%= render 'form', art: @art %>

<%= link_to 'Voir', @art %> |
<%= link_to 'Retour', arts_path %>

app/views/arts/index.html.erb
<style>
@import url('https://fonts.googleapis.com/css?family=Rock+Salt&display=swap');
</style>



<style>
@import url('https://fonts.googleapis.com/css?family=Ibarra+Real+Nova&display=swap');
</style> 




<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">Horror's Museum</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/">Accueil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/slideshows">Auteurs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/auteurs">Oeuvres</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>
  </div>
</nav>













<h3>Horror's Museum</h3>

<div class="container" >
  <div class="row" >
    <% @arts.each do |art| %>
      <div class="col-sm-4" >
        <div class="card" style="width: 18rem;">
          <img src="<%= art.photo %>" class="card-img-top" alt="<%= art.photo %>">
          <div class="card-body">
            <h5 class="card-title"><%= art.title %></h5>
            <p class="card-text"><%= art.comments %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= art.author %></li>
            <li class="list-group-item"><%= art.date %></li>
            <li class="list-group-item"><%= art.dimensions %></li>
          </ul>
        </div>
        <div class="card-body">
          <a href="#" class="card-link"><%= link_to 'Editer', edit_art_path(art) %></a>
          <a href="#" class="card-link"><%= link_to 'Voir', art %></a>
        </div>
      </div>

    <% end %>
  </div>
</div>
       



<a href="#" class="card-link"><%= link_to '', new_art_path %></a>

app/views/arts/new.html.erb
<h1>Ajouter une oeuvre</h1>

<%= render 'form', art: @art %>

<%= link_to 'Retour', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Auteur:</strong>
  <%= @art.author %>
</p>

<p>
  <strong>Titre:</strong>
  <%= @art.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @art.date %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @art.dimensions %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @art.photo %>
</p>

<p>
  <strong>Commentaires:</strong>
  <%= @art.comments %>
</p>

<%= link_to 'Editer', edit_art_path(@art) %> |
<%= link_to 'Retour', arts_path %>

app/views/auteurs/_form.html.erb
<%= simple_form_for(@auteur) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :author %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/auteurs/edit.html.erb
<h1>Editing Auteur</h1>

<%= render 'form', auteur: @auteur %>

<%= link_to 'Show', @auteur %> |
<%= link_to 'Back', auteurs_path %>

app/views/auteurs/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">Horror's Museum</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/">Accueil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/slideshows">Auteurs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/auteurs">Oeuvres</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>
  </div>
</nav>

<table>
  <thead>
    <tr>
    
    </tr>
  </thead>

  <tbody>
    <% @auteurs.each do |auteur| %>
   
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<div id="carousel-auteurs" style="width:35rem;" class="carousel slide" data-ride="carousel" >
  <ol class="carousel-indicators">
    <li data-target="#carousel-auteurs" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-auteurs" data-slide-to="1"></li>
    <li data-target="#carousel-auteurs" data-slide-to="2"></li>
    <li data-target="#carousel-auteurs" data-slide-to="3"></li>
    <li data-target="#carousel-auteurs" data-slide-to="4"></li>
    <li data-target="#carousel-auteurs" data-slide-to="5"></li>
    <li data-target="#carousel-auteurs" data-slide-to="6"></li>
    <li data-target="#carousel-auteurs" data-slide-to="7"></li>
    <li data-target="#carousel-auteurs" data-slide-to="8"></li>
    <li data-target="#carousel-auteurs" data-slide-to="9"></li>
    <li data-target="#carousel-auteurs" data-slide-to="10"></li>
    <li data-target="#carousel-auteurs" data-slide-to="11"></li>
    <li data-target="#carousel-auteurs" data-slide-to="12"></li>
    
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src=" https://upload.wikimedia.org/wikipedia/commons/2/24/Philippe_de_Champaigne_Still-Life_with_a_Skull.JPG" alt="slide 0">
     Still-Life with a Skull
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://shop.salvador-dali.org/media/catalog/category/SOMNI-CAUSAT-PEL-VOL-D_UNA-ABELLA-AL-VOLTANT-D_UNA-MAGRANA-UN-SEGON-ABANS-DE-DESPERTAR_2.jpg " alt="slide 1">
    Rêve causé par le vol d'une abeille autour d'une grenade, une seconde avant l'éveil
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://www.brevetdescolleges.fr/images/article/2013/05/la-guerre-otto-dix.jpg" alt="slide 2">
      La Guerre
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://www.tate.org.uk/art/images/work/T/T00/T00275_9.jpg" alt="slide 3">
     Light red over black
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://uploads7.wikiart.org/images/odilon-redon/the-smiling-spider-1891.jpg" alt="slide 4">
      The Smiling Spider
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://www.kazoart.com/blog/wp-content/uploads/2017/12/804px-The_Scream-803x675.jpg" alt="slide 5">
      Le Cri
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/1280px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg" alt="slide 6">
      Le radeau de la méduse
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://assets.catawiki.nl/assets/2018/2/7/0/b/8/0b88b196-07c1-4aa2-9f3e-4a736a44003f.jpg" alt="slide 7">
      Autoportrait mou avec du lard grillé
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Giuseppe_arcimboldo%2C_inverno%2C_1573%2C_01.JPG/800px-Giuseppe_arcimboldo%2C_inverno%2C_1573%2C_01.JPG"
     alt="slide 8">
     Hiver
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://www.beaux-arts.ca/sites/default/files/styles/ngc_scale_1200/public/mamanvers1.jpg?itok=Kg-Bw1Ml&timestamp=1556225313" alt="slide 9">
      Maman
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="http://www.peintre-analyse.com/corbeauxL450.jpg" alt="slide 10">
    Champ de blé aux corbeaux 
    </div>
   <div class="carousel-item">
      <img class="d-block w-100" src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Medusa_Murtola02.jpg/260px-Medusa_Murtola02.jpg" alt="slide 11">
    La meduse
    </div>
  </div>
  <a class="carousel-control-prev" href="#carousel-auteurs" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Précédent</span>
  </a>
  <a class="carousel-control-next" href="#carousel-auteurs" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Suivant</span>
  </a>
</div>

app/views/auteurs/new.html.erb
<h1>New Auteur</h1>

<%= render 'form', auteur: @auteur %>

<%= link_to 'Back', auteurs_path %>

app/views/auteurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @auteur.author %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @auteur.photo %>
</p>

<%= link_to 'Edit', edit_auteur_path(@auteur) %> |
<%= link_to 'Back', auteurs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exposition</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/slideshows/_form.html.erb
<%= simple_form_for(@slideshow) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :author %>
    <%= f.input :photo %>
    <%= f.input :description %>
    <%= f.input :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/slideshows/edit.html.erb
<h1>Editing Slideshow</h1>

<%= render 'form', slideshow: @slideshow %>

<%= link_to 'Show', @slideshow %> |
<%= link_to 'Back', slideshows_path %>

app/views/slideshows/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">Horror's Museum</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/">Accueil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/slideshows">Auteurs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/auteurs">Oeuvres</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>
  </div>
</nav>


<table>
  <thead>
    <tr>
      
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slideshows.each do |slideshow| %>
      <tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="carousel-auteurs" style="width:35rem; " class="carousel slide" data-ride="carousel" >
  <ol class="carousel-indicators">
    <li data-target="#carousel-auteurs" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-auteurs" data-slide-to="1"></li>
    <li data-target="#carousel-auteurs" data-slide-to="2"></li>
    <li data-target="#carousel-auteurs" data-slide-to="3"></li>
    <li data-target="#carousel-auteurs" data-slide-to="4"></li>
    <li data-target="#carousel-auteurs" data-slide-to="5"></li>
    <li data-target="#carousel-auteurs" data-slide-to="6"></li>
    <li data-target="#carousel-auteurs" data-slide-to="7"></li>
    <li data-target="#carousel-auteurs" data-slide-to="8"></li>
    <li data-target="#carousel-auteurs" data-slide-to="9"></li>
    <li data-target="#carousel-auteurs" data-slide-to="10"></li>
    <li data-target="#carousel-auteurs" data-slide-to="11"></li>
    
  </ol>
  <div class="carousel-inner" style="width: 35rem">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Salvador_Dali_NYWTS.jpg/260px-Salvador_Dali_NYWTS.jpg" alt="slide 0">
      Salvador Dali
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://www.repro-tableaux.com/images/template-pics/Biografien/portrait-giuseppe-arcimboldo.jpg" alt="slide 1">
      Giuseppe Arcimboldo  
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="http://www.moreeuw.com/histoire-art/munch-peintre.jpg" alt="slide 2">
      Edvard Munch   
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="http://womanns-world.com/wp-content/uploads/2015/08/louise_bourgeois-600x600.jpg" alt="slide 3">
      Louise Bourgeois   
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="http://larepubliquedeslivres.com/wp-content/uploads/2014/03/rothko-self-portrait-eastside-la-lifestyle.jpg" alt="slide 4">
      Mark Rothko
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJveSR2AzL22bfQxP6jMM-FElNNbPzgc2MxTqs1xDfkOVxBe8&s" alt="slide 5">
       Michel angelo Merisi da Caravaggio
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://uploads8.wikiart.org/temp/ab10e6cd-a7c7-45dc-af56-c177bc862aff.jpg!Portrait.jpg" alt="slide 6">
      Odilon Redon    
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://static.fnac-static.com/multimedia/Portraits/FR/NR/67/3e/0c/802407/1602-1.jpg" alt="slide 7">
      Otto Dix
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Philippe_de_Champaigne_003.jpg/220px-Philippe_de_Champaigne_003.jpg"
     alt="slide 8">
      Philippe de Champaigne
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Horace_Vernet%2C_Jean-Louis-Andr%C3%A9-Th%C3%A9odore_Gericault%2C_probably_1822_or_1823%2C_1998.84%2C_MET.jpg/260px-Horace_Vernet%2C_Jean-Louis-Andr%C3%A9-Th%C3%A9odore_Gericault%2C_probably_1822_or_1823%2C_1998.84%2C_MET.jpg" alt="slide 9">
      Théodore Géricault
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://i.f1g.fr/media/eidos/704x396_crop/2019/03/14/XVM8f9c44c6-45b1-11e9-993c-0f0d65ddc85d.jpg" alt="slide 10">
      Vincent Van Gogh
    </div>
   
  </div>
  <a class="carousel-control-prev" href="#carousel-auteurs" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Précédent</span>
  </a>
  <a class="carousel-control-next" href="#carousel-auteurs" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Suivant</span>
  </a>
</div>

app/views/slideshows/new.html.erb
<h1>New Slideshow</h1>

<%= render 'form', slideshow: @slideshow %>

<%= link_to 'Back', slideshows_path %>

app/views/slideshows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @slideshow.author %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @slideshow.photo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @slideshow.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @slideshow.text %>
</p>

<%= link_to 'Edit', edit_slideshow_path(@slideshow) %> |
<%= link_to 'Back', slideshows_path %>